export const APP_NAME = process.env.APP_NAME;
export const AUTHENTICATION_SERVICE_URL = process.env.AUTHENTICATION_SERVICE_URL;
export const ENCRYPTION_PBKDF2_KEYLEN = process.env.ENCRYPTION_PBKDF2_KEYLEN;
export const ENCRYPTION_PBKDF2_INTERATIONS = process.env.ENCRYPTION_PBKDF2_INTERATIONS;