export const APP_NAME = process.env.REACT_APP_APP_NAME;
export const AUTHENTICATION_SERVICE_URL = process.env.REACT_APP_AUTHENTICATION_SERVICE_URL;
export const ENCRYPTION_PBKDF2_KEYLEN = process.env.REACT_APP_ENCRYPTION_PBKDF2_KEYLEN;
export const ENCRYPTION_PBKDF2_INTERATIONS = process.env.REACT_APP_ENCRYPTION_PBKDF2_INTERATIONS;