export const APP_NAME = process.env.APP_NAME;
export const CM_SERVICE_URL = process.env.REACT_APP_CM_SERVICE_URL;
export const ENCRYPTION_PBKDF2_KEYLEN = process.env.REACT_APP_ENCRYPTION_PBKDF2_KEYLEN;
export const ENCRYPTION_PBKDF2_INTERATIONS = process.env.REACT_APP_ENCRYPTION_PBKDF2_INTERATIONS;